---
# - name: Configure Xorg to use Intel SCFB driver
#   become: yes
#   ansible.builtin.copy:
#     src: "{{ role_path }}/files/20-intel.conf"
#     dest: /usr/local/etc/X11/xorg.conf.d/20-intel.conf

# DRM driver does not need any config
- name: Don't use any Xorg Intel config
  become: yes
  file:
    dest: /usr/local/etc/X11/xorg.conf.d/20-intel.conf
    state: absent

- name: Configure Xorg to enable libinput touchpad tapping
  become: yes
  ansible.builtin.copy:
    src: "{{ role_path }}/files/40-libinput.conf"
    dest: /usr/local/etc/X11/xorg.conf.d/40-libinput.conf
