---
# Intel
- name: Load Intel CPU kernel modules
  become: yes
  community.general.sysrc:
    name: kld_list
    value: "{{ item }}"
    state: value_present
  with_items:
    - coretemp
    - cpuctl

# All Framework Systems support hwpstate_intel,
# which supercedes powerd
- name: Don't enable powerd
  become: yes
  community.general.sysrc:
    name: powerd_enable
    value: "NO"
    state: present

- name: Install Intel drivers
  become: yes
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - drm-61-kmod
    # - libva-intel-driver mesa-libs mesa-dri

- name: Configure Intel DRM driver
  become: yes
  community.general.sysrc:
    name: kld_list
    value: "i915kms"
    state: value_present

# Any framework system
- name: Make power button suspend instead of turning off
  become: yes
  ansible.posix.sysctl:
    name: hw.acpi.power_button_state
    value: "S3"
    state: present

- name: Configure Ethernet Expansion Card IPv4 DHCP
  become: yes
  community.general.sysrc:
    name: ifconfig_ue0
    value: "DHCP"
    state: present

- name: Configure Ethernet Expansion Card IPv6 DHCP
  become: yes
  community.general.sysrc:
    name: ifconfig_ue0_ipv6
    value: "inet6 accept_rtadv"
    state: present

- name: Install webcamd related packages
  become: yes
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - webcamd
    - v4l-utils
    - v4l_compat

- name: Load cuse driver
  become: yes
  community.general.sysrc:
    name: kld_list
    value: "cuse"
    state: value_present

- name: Add user to webcamd group
  become: yes
  user:
    name: '{{ ansible_user_id }}'
    groups: webcamd
    append: yes

- name: Enable webcamd service
  become: yes
  community.general.sysrc:
    name: webcamd_enable
    value: "YES"
    state: present
  
# Xorg
- name: Add user to video group
  become: yes
  user:
    name: '{{ ansible_user_id }}'
    groups: video
    append: yes

- name: Install Xorg packages
  become: yes
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - xorg

# GUI
- name: Install GUI packages
  become: yes
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - firefox
    - flameshot
    - noto-emoji
    - noto-tc
    - urwfonts
# TODO: Need to run this or add to config
# > xset fp+ /usr/local/share/fonts/urwfonts
# > xset fp rehash
