---
# Intel
- name: Load Intel CPU kernel modules
  become: yes
  community.general.sysrc:
    name: kld_list
    value: "{{ item }}"
    state: value_present
  with_items:
    - coretemp
    - cpuctl

# All Framework Systems support hwpstate_intel,
# which supercedes powerd
- name: Don't enable powerd
  become: yes
  community.general.sysrc:
    name: powerd_enable
    value: "NO"
    state: present

- name: Install Intel drivers
  become: yes
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - drm-61-kmod
    - gpu-firmware-kmod
    # - libva-intel-driver mesa-libs mesa-dri

- name: Configure Intel DRM driver
  become: yes
  community.general.sysrc:
    name: kld_list
    value: "i915kms"
    state: value_present
